#!/usr/bin/env bash
# Idempotent repository setup for the SIG Stakeholder Database dev environment.
#   - ensure the local MariaDB daemon is running
#   - create/seed the dev database and `users` table
#   - generate a local config.php pointing lusers.php at the dev database
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$HERE/.." && pwd)"

# PHP + MariaDB are provided by the base image (.cursor/Dockerfile).
echo "==> Ensuring MariaDB is running"
bash "$HERE/start-mariadb.sh"

echo "==> Applying dev schema and seed data"
sudo mysql < "$HERE/seed.sql"

CONFIG="$REPO_ROOT/config.php"
if [ ! -f "$CONFIG" ]; then
  echo "==> Writing local config.php (git-ignored)"
  cat > "$CONFIG" <<'PHP'
<?php
// Local development configuration (git-ignored). Generated by .cursor/install.sh.
return [
    'database' => [
        'host'     => '127.0.0.1',
        'port'     => 3306,
        'database' => 'sig',
        'username' => 'sig',
        'password' => 'sig',
        'charset'  => 'utf8mb4',
        'prefix'   => '',
    ],
];
PHP
else
  echo "==> config.php already present; leaving it untouched"
fi

echo "==> Verifying lusers.php can reach the database"
php -r '
$c = require "'"$REPO_ROOT"'/config.php";
$d = $c["database"];
$pdo = new PDO("mysql:host={$d["host"]};port={$d["port"]};dbname={$d["database"]};charset={$d["charset"]}", $d["username"], $d["password"], [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
$n = (int)$pdo->query("SELECT COUNT(*) FROM `{$d["prefix"]}users`")->fetchColumn();
echo "users table reachable: {$n} rows\n";
'

echo "==> Install complete"
